### ISSUE TITLE
Compile error BitCometAdapter.java:1: error: illegal character: '\ufeff'

### ISSUE THREAD

**Issue by bwitt** [erickok/transdroid#627]
When I try to compile transdroid in android studio I get this error:

```
/home/bwitt/src/transdroid/app/src/main/java/org/transdroid/daemon/adapters/bitComet/BitCometAdapter.java:1: error: illegal character: '\ufeff'
﻿/*
^
/home/bwitt/src/transdroid/app/src/main/java/org/transdroid/daemon/adapters/bitComet/BitCometAdapter.java:18: error: class, interface, or enum expected
package org.transdroid.daemon.adapters.bitComet;
        ^
```

I think there's an unprintable character there that's causing problems.

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/200054857-12bc7153-a7dc-4809-8a16-f1799e109422.png)

![image](https://user-images.githubusercontent.com/6442439/200054817-abcd5c04-7821-45de-bfc8-216d1c8feeda.png)

**Comment by 1265578519** [comment]
utf-8
uft-8-sig（BOM: ByteOrder Mark）

**Comment by bwitt** [comment]
I think this was introduced in https://github.com/erickok/transdroid/pull/621
